### ISSUE TITLE
ClassNotFoundException when running WordCountJob

### ISSUE THREAD

**Issue by linjiyuan90** [snowplow-archive/scalding-example-project#5]
Hi, sorry to bother you, but i have problem when running:

```
hadoop jar target/scalding-example-project-0.0.4.jar com.snowplowanalytics.hadoop.scalding.WordCountJob --local
```

The error is 

```
Exception in thread "main" java.lang.ClassNotFoundException: com.snowplowanalytics.hadoop.scalding.WordCountJob
```

Can you help me figure it out?
Thanks in advance!

**Comment by alexanderdean** [comment]
Hi @linjiyuan90, can you post support questions to the Snowplow user group please? snowplow-user@googlegroups.com

Thanks, Alex
