### ISSUE TITLE
Different hadoop version?

### ISSUE THREAD

**Issue by dmiletic** [snowplow-archive/scalding-example-project#8]
Can this project be built with different hadoop version (1.0.3 for example)?

**Comment by alexanderdean** [comment]
We align the Hadoop version with the one used inside Scalding:

https://github.com/twitter/scalding/blob/0.9.1/project/Build.scala#L175

If you change the Hadoop version in this project, Scalding is still going to try and pull in the other Hadoop version. Not sure what will happen at `sbt assembly` time, or at runtime. Give it a try!
